trigger:
- main

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'
  apiProject: 'back-end/KramarDev.Quiz.WebAPI/KramarDev.Quiz.WebAPI.csproj'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '10.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '$(apiProject)'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '$(apiProject)'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Publish API'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(apiProject)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api --no-build'
    zipAfterPublish: true

- task: AzureWebApp@1
  displayName: 'Deploy API to Azure Web App'
  inputs:
    azureSubscription: 'quiz-it-connection'
    appType: 'webApp'
    appName: 'quiz-it-api'
    package: '$(Build.ArtifactStagingDirectory)/api/**/*.zip'
    deploymentMethod: 'zipDeploy'